@extends('admin.layouts.app')
@section('title', 'Order '.$order->order_number)
@section('active_nav', 'orders')
@section('eyebrow', 'The details behind the delivery')
@section('heading', 'Order details.')
@section('description', $order->order_number)
@section('actions')<a class="wg-admin-button" href="{{ route('admin.orders.index') }}">&larr; All orders</a>@endsection
@section('content')
    @include('admin.orders._workspace')
    <div class="ao-order-meta"><p>Placed {{ $order->created_at->format('d M Y, H:i') }} · Updated {{ $order->updated_at->format('d M Y, H:i') }}</p><span class="ao-badge" data-state="{{ $order->payment_status }}">{{ ucfirst($order->payment_status) }}</span><span class="ao-badge" data-state="{{ $order->status }}">{{ ucfirst($order->status) }}</span></div>
    <div class="ao-detail-grid"><div class="ao-detail-main">
        <section class="category-panel" aria-labelledby="items-title"><div class="category-panel__heading"><div><h2 id="items-title">Order items</h2><p>{{ $order->items->sum('quantity') }} items · Details saved at purchase</p></div></div><ul class="ao-items">@foreach($order->items as $item)<li class="ao-item"><span class="ao-item__mark" aria-hidden="true">W</span><div class="ao-item__identity"><h3>{{ $item->product_name }}</h3><p>SKU: {{ $item->product_sku ?? 'Not specified' }}</p><small>{{ $order->currency }} {{ number_format($item->unit_price, 2) }} each</small></div><span class="ao-item__quantity">Qty {{ $item->quantity }}</span><strong>{{ $order->currency }} {{ number_format($item->line_total, 2) }}</strong></li>@endforeach</ul></section>
        <section class="category-panel" aria-labelledby="payment-title"><div class="category-panel__heading"><h2 id="payment-title">Payment summary</h2><span class="ao-badge">{{ $order->payment_method === 'cod' ? 'Cash on Delivery' : $order->payment_method }}</span></div><div class="category-panel__body"><dl class="ao-totals">@foreach(['subtotal'=>'Subtotal','discount_amount'=>'Discount','delivery_charge'=>'Delivery','total'=>'Order total'] as $field=>$label)<div class="{{ $field === 'total' ? 'ao-totals__total' : '' }}"><dt>{{ $label }}</dt><dd>{{ $order->currency }} {{ number_format($order->$field, 2) }}</dd></div>@endforeach</dl>
            @if($paymentTransitions)<form method="POST" action="{{ route('admin.orders.update', $order) }}" class="ao-management-form">@csrf @method('PATCH')<input type="hidden" name="action" value="payment"><input type="hidden" name="expected_status" value="{{ $order->status }}"><input type="hidden" name="expected_payment" value="{{ $order->payment_status }}"><input type="hidden" name="payment_status" value="{{ $paymentTransitions[0] }}"><label class="ao-confirm"><input type="checkbox" required> I confirm that {{ $paymentTransitions[0] === 'paid' ? 'payment has been collected' : 'the refund has been completed' }}.</label><button class="wg-admin-button" type="submit">Mark {{ $paymentTransitions[0] }}</button></form>@endif
            <p class="ao-small-note">COD orders can be dispatched before payment. Record payment after delivery. Payment updates record money already collected or refunded; they do not transfer money.</p>
            @if($order->status === 'cancelled' && $order->payment_status === 'paid')<p class="category-feedback" role="status">This cancelled order still has a paid balance. Arrange the refund before marking it refunded.</p>@endif
        </div></section>
    </div><aside class="ao-detail-side" aria-label="Customer and order management">
        <section class="category-panel" aria-labelledby="customer-title"><div class="category-panel__heading"><h2 id="customer-title">Customer &amp; delivery</h2></div><div class="category-panel__body"><div class="ao-customer"><div><h3>{{ $order->customer_name }}</h3><p>{{ $order->customer_phone }}<br>{{ $order->customer_email ?? 'No email provided' }}</p></div></div><div class="ao-address"><h3>Delivery address</h3><p>{{ $order->address }}<br>{{ $order->area }}, {{ $order->city }}<br>Zone: {{ $order->delivery_zone === 'dhaka' ? 'Inside Dhaka' : 'Outside Dhaka' }}</p>@if($order->notes)<h3>Customer instructions</h3><p>{{ $order->notes }}</p>@endif</div></div></section>
        <section class="category-panel" aria-labelledby="status-title"><div class="category-panel__heading"><h2 id="status-title">Manage order</h2></div><div class="category-panel__body">
            @if($transitions)<form method="POST" action="{{ route('admin.orders.update', $order) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="status"><input type="hidden" name="expected_status" value="{{ $order->status }}"><input type="hidden" name="expected_payment" value="{{ $order->payment_status }}"><label class="category-field">Next status<select name="status" required><option value="">Choose next step</option>@foreach($transitions as $state)<option value="{{ $state }}" @selected(old('status') === $state)>{{ ucfirst($state) }}</option>@endforeach</select></label><label class="ao-confirm"><input type="checkbox" required> I have checked the order and confirm this change.</label><button class="wg-admin-button wg-admin-button--primary" type="submit">Update status</button></form><p class="ao-small-note">Cancellation is available before shipping and restores quantities to existing products once. Deleted products remain in the order history.</p>@else<p class="ao-small-note">This order is {{ $order->status }}. No further fulfillment changes are available.</p>@endif
        </div></section>
    </aside></div>
@endsection
