<div class="category-panel category-not-found" data-not-found hidden><h2>Product not found.</h2><p>This product may belong to another browser tab.</p><a class="wg-admin-button" href="{{ url('/admin/products') }}">Back to products</a></div>
<form class="category-form ap-form" data-product-form data-mode="{{ $mode }}" data-id="{{ request()->route('product') }}">
    <div class="category-form__main">
        <section class="category-panel" aria-labelledby="product-details-title"><div class="category-panel__heading"><div><h2 id="product-details-title">Product details</h2><p>The essentials your customers need to know.</p></div><span class="category-section-number" aria-hidden="true">01</span></div><div class="category-panel__body">
            <label class="category-field" for="ap-name">Product name <span aria-hidden="true">*</span><input id="ap-name" name="name" required maxlength="100" placeholder="e.g. Swedish Wall" autocomplete="off"></label>
            <div class="category-field"><div class="category-field__label"><label for="ap-slug">URL slug <span aria-hidden="true">*</span></label><button class="category-text-button" type="button" data-generate-slug>Generate from name</button></div><input id="ap-slug" name="slug" required maxlength="120" pattern="[a-z0-9]+(-[a-z0-9]+)*" spellcheck="false" placeholder="swedish-wall" aria-describedby="ap-slug-help"><small id="ap-slug-help">Use lowercase letters, numbers, and hyphens. Each product needs a unique slug.</small></div>
            <label class="category-field" for="ap-description">Description <span class="category-optional">Optional</span><textarea id="ap-description" name="description" rows="6" maxlength="2000" placeholder="Introduce the product and what makes it useful."></textarea><span class="category-field__hint"><small>Keep it useful, honest, and easy to read.</small><small data-description-count>0 / 2000</small></span></label>
            <div class="ap-fields-two"><label class="category-field" for="ap-dimensions">Dimensions <span class="category-optional">Optional</span><input id="ap-dimensions" name="dimensions" maxlength="120" placeholder="Height × width × depth, with units"></label><label class="category-field" for="ap-material">Material <span class="category-optional">Optional</span><input id="ap-material" name="material" maxlength="120" placeholder="Add verified material details"></label></div>
        </div></section>

        <section class="category-panel" aria-labelledby="product-media-title"><div class="category-panel__heading"><div><h2 id="product-media-title">Cover image</h2><p>Give your product a clear first impression.</p></div><span class="category-section-number" aria-hidden="true">02</span></div><div class="category-panel__body"><div class="category-upload"><span class="category-upload__icon" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 6-6 4 4 3-3 5 5"/></svg></span><label for="ap-image">Choose a product image</label><p id="ap-image-help">JPG, PNG, or WebP, up to 1 MB. Keep the whole product in view.</p><input type="file" id="ap-image" accept="image/jpeg,image/png,image/webp" aria-describedby="ap-image-help ap-image-error"><p id="ap-image-error" class="category-error" role="alert" hidden></p></div><div class="category-image-meta"><span data-image-name>No image selected</span><button class="category-text-button" type="button" data-remove-image hidden>Remove image</button></div></div></section>

        <section class="category-panel" aria-labelledby="product-pricing-title"><div class="category-panel__heading"><div><h2 id="product-pricing-title">Pricing &amp; inventory</h2><p>Leave unknown values blank while your product is a draft.</p></div><span class="category-section-number" aria-hidden="true">03</span></div><div class="category-panel__body">
            <div class="ap-fields-two"><label class="category-field" for="ap-price">Price<input id="ap-price" name="price" type="number" min="0" max="99999999" step="0.01" inputmode="decimal" placeholder="0.00"></label><label class="category-field" for="ap-currency">Currency<select id="ap-currency" name="currency"><option value="">Choose currency</option><option value="SEK">SEK — Swedish krona</option><option value="EUR">EUR — Euro</option><option value="USD">USD — US dollar</option><option value="BDT">BDT — Bangladeshi taka</option></select></label></div>
            <div class="ap-fields-two"><label class="category-field" for="ap-sku">SKU <span class="category-optional">Optional</span><input id="ap-sku" name="sku" maxlength="60" placeholder="WG-WALL-001" autocomplete="off"><small>A unique internal reference for this product.</small></label><label class="category-field" for="ap-stock">Stock quantity<input id="ap-stock" name="stock" type="number" min="0" max="999999" step="1" inputmode="numeric" placeholder="Not set"><small>Enter 0 for no stock. Blank means unknown.</small></label></div>
        </div></section>
    </div>
    <aside class="category-form__side" aria-label="Product organization and preview">
        <section class="category-panel" aria-labelledby="product-organization-title"><div class="category-panel__heading"><h2 id="product-organization-title">Organization</h2></div><div class="category-panel__body"><label class="category-field" for="ap-status">Status<select id="ap-status" name="status"><option value="draft">Draft</option><option value="active">Active</option></select><small>Active is a preview status, not a live publication.</small></label><label class="category-field" for="ap-category">Category <span aria-hidden="true">*</span><select id="ap-category" name="category" required><option value="">Choose category</option></select><small>Includes categories saved in this tab.</small></label></div></section>
        <section class="category-panel category-live-preview" aria-labelledby="product-preview-title"><div class="category-panel__heading"><h2 id="product-preview-title">Product preview</h2><span class="category-preview-live">Live</span></div><div class="category-panel__body"><div class="category-cover ap-preview-cover"><img data-preview-image width="400" height="400" alt="Product cover preview" hidden><span data-preview-placeholder aria-hidden="true">W</span><span class="category-badge" data-preview-status>Draft</span></div><p class="ap-preview-category" data-preview-category>Choose a category</p><h3 data-preview-name>Your product name</h3><p data-preview-description>A short description will appear here.</p><p class="ap-preview-price" data-preview-price>Price not set</p></div></section>
    </aside>
    <div class="category-form__actions"><p>* Required fields <span class="category-actions-note">&middot; Saves to this tab only</span></p><div><a class="wg-admin-button" href="{{ url('/admin/products') }}">Cancel</a><button type="submit" class="wg-admin-button wg-admin-button--primary" data-save disabled>{{ $mode === 'create' ? 'Create preview' : 'Save changes' }} <span aria-hidden="true">&rarr;</span></button></div></div>
    <noscript><p class="category-notice">Enable JavaScript to use the product form preview.</p></noscript>
</form>
